export const backgroundColors = {
  normal: "bg-normal/50",
  fighting: "bg-fighting/50",
  flying: "bg-flying/50",
  poison: "bg-poison/50",
  ground: "bg-ground/50",
  rock: "bg-rock/50",
  bug: "bg-bug/50",
  ghost: "bg-ghost/50",
  steel: "bg-steel/50",
  fire: "bg-fire/50",
  water: "bg-water/50",
  grass: "bg-grass/50",
  electric: "bg-electric/50",
  psychic: "bg-psychic/50",
  ice: "bg-ice/50",
  dragon: "bg-dragon/50",
  dark: "bg-dark/50",
  fairy: "bg-fairy/50",
}
