export const backgroundColors = {
  normal: "bg-normal/75",
  fighting: "bg-fighting/75",
  flying: "bg-flying/75",
  poison: "bg-poison/75",
  ground: "bg-ground/75",
  rock: "bg-rock/75",
  bug: "bg-bug/75",
  ghost: "bg-ghost/75",
  steel: "bg-steel/75",
  fire: "bg-fire/75",
  water: "bg-water/75",
  grass: "bg-grass/75",
  electric: "bg-electric/75",
  psychic: "bg-psychic/75",
  ice: "bg-ice/75",
  dragon: "bg-dragon/75",
  dark: "bg-dark/75",
  fairy: "bg-fairy/75",
};
