export const backgroundColors = {
  normal: "bg-normal",
  fighting: "bg-fighting text-white ring-black",
  flying: "bg-flying",
  poison: "bg-poison text-white ring-black",
  ground: "bg-ground",
  rock: "bg-rock",
  bug: "bg-bug",
  ghost: "bg-ghost text-white ring-black",
  steel: "bg-steel",
  fire: "bg-fire",
  water: "bg-water",
  grass: "bg-grass",
  electric: "bg-electric",
  psychic: "bg-psychic",
  ice: "bg-ice",
  dragon: "bg-dragon text-white ring-black",
  dark: "bg-dark text-white ring-black",
  fairy: "bg-fairy",
}
